### ISSUE TITLE
Change gravatar profile image to local server

### ISSUE THREAD

**Issue by repowebsite** [royduin/fastr#1]
The Project is in excellent working order, I am learning a lot from it.
I would like to request some support or even insert a new function.

I noticed that to insert a profile image you need to create account in Gravatar, with this you would have to change totally on an outside server.

My request if possible, would be like inserting a profile image, directly uploading my computer, and write to the user database.

How could you enter this function?

I'm a student, I'm still learning PHP, sorry for the ignorance.

Thank you!

**Comment by royduin** [comment]
Sorry, can't help you with this. I'm not going to build new features but everything is present in the project to do this yourself. Image uploads are already there, create a new column in the users table and copy and edit some code from other parts of the project into the profile part.
